#!/bin/bash

echo "========================================="
echo "========================================="
echo -e "\e[0;2s Elite Hackers Company LATAM\e[0m" 
echo "========================================="
echo "========================================="
figlet ELITE
figlet HACKERS
figlet COMPANY 
echo "========================================="
echo "========================================="
figlet LALO
echo "========================================="
sleep 2
figlet C+ DOMAINS
echo "========================================="
echo "========================================="

echo -e "\e[0;7s CODES_\e[0m"
sleep 2
setterm -foreground yellow
echo -e "\e[0;10s vt_domains_relationships_\e[0m"
echo -e "\e[0;10s vt_domains_graphs_\e[0m"

echo -e "\e[0;10s vt_domains_collections\e[0m"

echo -e "\e[0;10s vt_domains_siblings\e[0m"

echo -e "\e[0;10s vt_domains_parent_\e[0m"

echo -e "\e[0;10s ls-cdTool-Web-RS &&\e[0m"

echo -e "\e[0;10s l s python,2 Real-DNS\e[0m"

echo -e "\e[0;10s vtsearch \e[0m"

echo -e "\e[0;10s cat list_of_domains |-vt_domain_\e[0m"

echo "========================================="
echo "========================================="
figlet ELITE 
figlet HACKERS 
figlet COMPANY
echo "========================================="
echo "========================================="
