#!/bin/bash

echo "========================================="
echo "========================================="
setterm -foreground cyan
echo -e "\e[0;2s Elite Hackers Company LATAM\e[0m" 
echo "========================================="
echo "========================================="
setterm -foreground red
figlet ELITE
figlet HACKERS
figlet COMPANY 
echo "======================================================== "========================================="
echo "========================================================"
setterm -foreground yellow
figlet LALO
echo "======================================================== "========================================="
figlet WEB EXCLUSIVE
figlet FOR HACKERS
figlet ALERT ALERT
echo "========================================================
echo "========================================================
sleep 2
setterm -foreground red
figlet C+ DOMAINS
echo "======================================================== "========================================="
echo "======================================================== "========================================="
echo -e "\e[0;7s CODES_\e[0m"
sleep 2
setterm -foreground yellow
echo -e "\e[0;10s vt domain relationships \e[0m"
echo -e "\e[0;10s vt domain graphs \e[0m"

echo -e "\e[0;10s vt domain collections\e[0m"

echo -e "\e[0;10s vt domain siblings\e[0m"

echo -e "\e[0;10s vt domain parent\e[0m"

echo -e "\e[0;10s ls-cdTool-Web-RS &&\e[0m"

echo -e "\e[0;10s l s python,2 Real-DNS\e[0m"

echo -e "\e[0;10s vt search \e[0m"

echo -e "\e[0;10s cat list of domains |-vt domain\e[0m"

echo "========================================================"========================================="
echo "======================================================== "========================================="
setterm -foreground purple
figlet ELITE 
figlet HACKERS 
figlet COMPANY
echo "========================================="
echo "========================================="
